apiVersion: v1
kind: Namespace
metadata:
  name: my-mesh
  labels:
    istio-injection: enabled
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
  namespace: my-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            memory: 256Mi
        livenessProbe:
          httpGet:  # Use httpGet instead of tcpSocket
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet: # Use httpGet instead of tcpSocket
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-service
  namespace: my-mesh
spec:
  selector:
    app: simple-http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP