apiVersion: v1
kind: Namespace
metadata:
  name: my-mesh
  labels:
    istio-injection: enabled
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
  namespace: my-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: us-east4-docker.pkg.dev/db-demo-gke-ent/my-docker/dummy-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-service
  namespace: my-mesh
spec:
  selector:
    app: simple-http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP