apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: my-mesh
  labels:
    app: simple-pod
spec:
  containers:
  - name: simple-pod
    image: nginx:alpine
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 256Mi
        cpu: 250m
    ports:
    - containerPort: 80
