apiVersion: v1
kind: Namespace
metadata:
  name: test
---    
apiVersion: v1
kind: Pod
metadata:
  name: curl-test-pod
  namespace: test
spec:
  initContainers:
  - name: install-iputils
    image: curlimages/curl:latest  # We can use the same image
    command:
    - sh
    - -c
    - |
      apk add --no-cache iputils
    securityContext:
      runAsUser: 0  # Run this init container as root
  containers:
  - name: curl-test-container
    image: curlimages/curl:latest
    command: ["sleep", "infinity"]
    stdin: true
    tty: true
  restartPolicy: Never
